-- ============================================================================
-- S-MIB — Supabase schema (Day 3): projects, steps, progress, certificates,
-- achievements catalog + user_achievements. Columns map 1:1 to the model
-- toRow()/fromRow() in src/models/. Run AFTER schema.sql, then seed.sql.
-- ============================================================================

-- ── projects ────────────────────────────────────────────────────────────────
create table if not exists public.projects (
  id           bigint generated by default as identity primary key,
  title        text not null,
  category     text,
  difficulty   text default 'Easy' check (difficulty in ('Easy','Medium','Hard')),
  duration     text,
  description  text,
  emoji        text default '🛠️',
  color        text default 'teal-img',
  creator_id   uuid references public.profiles (id) on delete set null,
  creator_name text,
  status       text not null default 'draft' check (status in ('draft','review','published','rejected')),
  enrolled     integer default 0,
  completion   integer default 0,
  rating       numeric default 0,
  cover_url    text,
  created_at   timestamptz default now(),
  type         text not null default 'guided' check (type in ('guided','open')),
  step_count   integer not null default 0
);

-- ── steps (PK = project_id + step_n) ─────────────────────────────────────────
create table if not exists public.steps (
  project_id     bigint not null references public.projects (id) on delete cascade,
  step_n         integer not null check (step_n >= 1),
  title          text not null,
  instruction    text default '',
  tip            text,
  materials      jsonb default '[]'::jsonb,
  xp             integer default 0,
  video_url      text,
  proof_required boolean default true,
  primary key (project_id, step_n)
);

-- ── progress (one row per user+project) ──────────────────────────────────────
create table if not exists public.progress (
  id                     bigint generated by default as identity primary key,
  user_id                uuid not null references public.profiles (id) on delete cascade,
  project_id             bigint not null references public.projects (id) on delete cascade,
  completed_step_numbers integer[] default '{}',
  xp_earned              integer default 0,
  last_step_at           timestamptz,
  is_bookmarked          boolean default false,
  is_manually_completed  boolean default false,
  step_proofs            jsonb default '{}'::jsonb,
  step_ratings           jsonb default '{}'::jsonb,
  unique (user_id, project_id)
);

-- ── certificates ─────────────────────────────────────────────────────────────
create table if not exists public.certificates (
  id            bigint generated by default as identity primary key,
  code          text unique not null,
  project_id    bigint references public.projects (id) on delete set null,
  user_id       uuid not null references public.profiles (id) on delete cascade,
  project_title text,
  user_name     text,
  issued_at     timestamptz default now(),
  verify_url    text,
  unique (user_id, project_id)
);

-- ── achievements (catalog) ───────────────────────────────────────────────────
create table if not exists public.achievements (
  code        text primary key,
  tier        text not null check (tier in ('bronze','silver','gold','legendary')),
  icon        text,
  name        text not null,
  description text
);

-- ── user_achievements ────────────────────────────────────────────────────────
create table if not exists public.user_achievements (
  user_id          uuid not null references public.profiles (id) on delete cascade,
  achievement_code text not null references public.achievements (code) on delete cascade,
  earned_at        timestamptz default now(),
  primary key (user_id, achievement_code)
);

-- ── streak support on profiles ───────────────────────────────────────────────
alter table public.profiles add column if not exists last_active_on date;

-- ── Row Level Security ───────────────────────────────────────────────────────
alter table public.projects          enable row level security;
alter table public.steps             enable row level security;
alter table public.progress          enable row level security;
alter table public.certificates      enable row level security;
alter table public.achievements      enable row level security;
alter table public.user_achievements enable row level security;

-- projects: anyone may read published rows; owners read their own.
drop policy if exists "projects_read" on public.projects;
create policy "projects_read" on public.projects
  for select using (status = 'published' or creator_id = auth.uid());

-- steps: readable when the parent project is readable.
drop policy if exists "steps_read" on public.steps;
create policy "steps_read" on public.steps
  for select using (exists (
    select 1 from public.projects p
    where p.id = steps.project_id
      and (p.status = 'published' or p.creator_id = auth.uid())
  ));

-- progress: owner full access.
drop policy if exists "progress_rw" on public.progress;
create policy "progress_rw" on public.progress
  for all using (user_id = auth.uid()) with check (user_id = auth.uid());

-- certificates: owner read + insert.
drop policy if exists "certs_select_own" on public.certificates;
create policy "certs_select_own" on public.certificates
  for select using (user_id = auth.uid());
drop policy if exists "certs_insert_own" on public.certificates;
create policy "certs_insert_own" on public.certificates
  for insert with check (user_id = auth.uid());

-- achievements catalog: public read.
drop policy if exists "achievements_read" on public.achievements;
create policy "achievements_read" on public.achievements
  for select using (true);

-- user_achievements: owner read.
drop policy if exists "user_achievements_select_own" on public.user_achievements;
create policy "user_achievements_select_own" on public.user_achievements
  for select using (user_id = auth.uid());
